### ISSUE TITLE
Is there a way to get the crop cordinates?

### ISSUE THREAD

**Issue by akashkamboj** [Stakenborg/BASSquareCropper#1]
Hey 

I love the way you built this. Simple and easy to use, is there a way to get the crop coordinates. I want to store both the images on server and want the coordinates so that i can crop manually on server-side.

**Comment by Stakenborg** [comment]
Hey Akash,

Thanks! Glad you like it!

I'm sure I can whip something up for returning coordinates, you're probably not the only person interested in them. Are you thinking something like a CGPoint that gives you the top left point of the cropped image within the original? With that plus the size of the new image you'd have your crop.

Alternatively, I could just fire back a full CGRect with the top left point as well as the size of the new image.

Which works better for you?

-Brandon

**Comment by akashkamboj** [comment]
Well In my case I will need the CGRect which gives me the exact position of the thumb, as well as width, height with the resized image ratio. exactly the same way as UIImagePickerController. UIImagePickerController is working fine in my case. only problem with that is on iPAD there's no way to make the crop area as square.

**Comment by Stakenborg** [comment]
Gotcha. I'll definitely make this happen in the coming days.

Thanks for the suggestion!

-Brandon

**Comment by akashkamboj** [comment]
Thanx. I know it's an awkward question for an open source project :) but Do you have a milestone date for this? Actually I needed this urgently for a project.

**Comment by Stakenborg** [comment]
I'm tinkering with it right now. Should have something shortly.

-Brandon

**Comment by Stakenborg** [comment]
Oops. I'm about to commit some changes which actually also addressed a somewhat nasty bug fix.

The delegate is going to return the cropper object now which has a property for that crop rect. You can grab it from there. I've updated the example with an...example...of this.

You can just snag the cropper from my git or you can wait for it on pods (assuming thats what you're using).

Thanks!

-Brandon

**Comment by Stakenborg** [comment]
Alright, the new cropper is up. I can't move it over to Cocoapods yet because they're transitioning how you submit pods, so that might be a couple of days.

At any rate, unless something is broken I'm going to mark this one as closed.

Please reopen if it doesn't fit what you're looking for.

Thanks for the suggestion!

-Brandon

**Comment by akashkamboj** [comment]
hi @Stakenborg. Thanks for quick release. It's working almost fine in the first test. Only problem is that crop Rect is 2x. I guess it's because of Retina display.

**Comment by Stakenborg** [comment]
Hey @akashkamboj 

Glad it's working for you (hopefully almost fine has turned into fine by now)!

As far as the CGRect being 2x, I just realized I was using an @2x image in the example, so I was compensating for that in the crop rect. I've fixed it so it'll return proper coordinates against any image now.

Let me know if this is still buggy for you, and thanks for the feedback!

-Brandon

**Comment by akashkamboj** [comment]
hey @Stakenborg 
It's working absolutely fine now. Thanks once again for quick fixes.
