### ISSUE TITLE
Not working on iPad landscape 

### ISSUE THREAD

**Issue by akashkamboj** [Stakenborg/BASSquareCropper#2]
hey @Stakenborg 

I found another issue. on iPAD landscape it's not working. I guess it's because of NSLayoutConstraints.

**Comment by Stakenborg** [comment]
Hey @akashkamboj 

Thanks again! You're like my defacto QA guy now. I'll handle this right now.

-Brandon

**Comment by Stakenborg** [comment]
This has been fixed, committed, and submitted to Cocoapods. The cropper now forces portrait.

Let me know if you find anything else.

Thanks for all the help!

-Brandon
