### ISSUE TITLE
ios 8 issues

### ISSUE THREAD

**Issue by akashkamboj** [Stakenborg/BASSquareCropper#3]
Hi there once again

I am facing a strange issue in iOS8, using the crop image with filters  etc. some images are crashing the app. i researched on it and it seems that UIGraphicsBeginImageContextWithOptions  is apparently using a lot of memory in ios8. so i try changing the approach to CGImage with following code:

```

@implementation UIImage (Crop)

- (instancetype)cropImageWithRect:(CGRect)rect {
    double (^rad)(double) = ^(double deg) {
        return deg / 180.0 * M_PI;
    };

    CGAffineTransform rectTransform;
    switch (self.imageOrientation) {
        case UIImageOrientationLeft:
            rectTransform = CGAffineTransformTranslate(CGAffineTransformMakeRotation(rad(90)), 0, -self.size.height);
            break;
        case UIImageOrientationRight:
            rectTransform = CGAffineTransformTranslate(CGAffineTransformMakeRotation(rad(-90)), -self.size.width, 0);
            break;
        case UIImageOrientationDown:
            rectTransform = CGAffineTransformTranslate(CGAffineTransformMakeRotation(rad(-180)), -self.size.width, -self.size.height);
            break;
        default:
            rectTransform = CGAffineTransformIdentity;
    };
    rectTransform = CGAffineTransformScale(rectTransform, self.scale, self.scale);

    CGImageRef imageRef = CGImageCreateWithImageInRect([self CGImage], CGRectApplyAffineTransform(rect, rectTransform));
    UIImage *result = [UIImage imageWithCGImage:imageRef scale:self.scale orientation:self.imageOrientation];
    CGImageRelease(imageRef);

    return result;
}

@end

```

And the app didn't crash with this approach, as well as taking less memory and time. However I am not able to get the correct formula for the crop area and scale. 

I think the CGImageRef will be a faster solution anyways. What do you think?

**Comment by Stakenborg** [comment]
Thanks for the follow up. I'll have to look into this at some point in the next couple days. I'll let you know what I find.

Thanks!

**Comment by Streek** [comment]
My clients app is crashing a ton because of the memory issues on older devices.  I came up with a similar issue and fix but haven't been able to put a lot of time into it.

**Comment by Stakenborg** [comment]
I'm going to have some time to look into this over the weekend, finally. I'll see if I can find an alternative that is less of a memory hog.

Thanks for the info guys!

-Brandon

**Comment by Stakenborg** [comment]
I've come up with a CGImage solution for this:

```
- (void)cropImage
{
    UIImage *croppedImage = nil;

    _cropRect.size.width = (CGFloat)round(CGRectGetWidth(self.croppingOverlayView.bounds)/self.zoomScale);
    _cropRect.size.height = (CGFloat)round(CGRectGetHeight(self.croppingOverlayView.bounds)/self.zoomScale);
    _cropRect.origin.x = (CGFloat)round((self.contentOffset.x + self.contentInset.left)/self.zoomScale);
    _cropRect.origin.y = (CGFloat)round((self.contentOffset.y + self.contentInset.top)/self.zoomScale);
    CGImageRef imageRef = CGImageCreateWithImageInRect(self.imageToCrop.CGImage, _cropRect);
    croppedImage = [UIImage imageWithCGImage:imageRef];
    CGImageRelease(imageRef);

    [self.squareCropperDelegate squareCropperDidCropImage:croppedImage inCropper:self];
}
```

If you wouldn't mind giving it a shot for me, you should just be able to replace the cropImage function with this. No need to modify anything else.

Thanks,

-Brandon
