### ISSUE TITLE
Pinch zoom not working when the image is square

### ISSUE THREAD

**Issue by ghost** [Stakenborg/BASSquareCropper#4]
I have downloaded and then installed the library.

It was working fine until yesterday, but somehow the pinch zoom is not working right now for the square image, it is working fine for non-square image.

**Comment by Stakenborg** [comment]
Hey @dipen0807 ,

I just tried this using the example code after resizing the example image to be 800x800 and it worked. Only thing I can think is the source image you're using is the same size or smaller as the minimum side length you're giving it, which will stop it from zooming.

Thanks for reaching out!

-Brandon
